In [2]:
import pandas as pd

In [3]:
#Load CSV
data = pd.read_csv('spam.csv', encoding="latin1")
data.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [4]:
columns_to_keep = ["v1","v2"]
data = data[columns_to_keep]
data.columns = ['label', 'message']
data.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
print(data['label'].value_counts())

label
ham     4825
spam     747
Name: count, dtype: int64

In [6]:
import string
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

In [7]:
# Simple text cleaning
data['message'] = data['message'].str.lower().str.replace(r'[^a-z\s]', '', regex=True)

In [8]:
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    data['message'], data['label'], test_size=0.2, random_state=42
)

In [9]:
# Convert text to numeric features
vectorizer = CountVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

In [10]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

model = MultinomialNB()
model.fit(X_train_vec, y_train)

# Predict
y_pred = model.predict(X_test_vec)

# Evaluate
print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.979372197309417
[[960   5]
 [ 18 132]]
              precision    recall  f1-score   support

         ham       0.98      0.99      0.99       965
        spam       0.96      0.88      0.92       150

    accuracy                           0.98      1115
   macro avg       0.97      0.94      0.95      1115
weighted avg       0.98      0.98      0.98      1115

In [17]:
sample_email = ["Win a free iPhone!"]
sample_vec = vectorizer.transform(sample_email)
prediction = model.predict(sample_vec)
print(prediction)  # should return 'spam'

['spam']

In [13]:
import pickle

In [15]:
pickle.dump(model,open("model.pkl","wb"))
pickle.dump(vectorizer, open("vectorizer.pkl","wb"))